//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.01 at 04:50:33 PM IST 
//


package com.koopid.ccmm.wsdl.ci_contact;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfCIClosedRCReadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfCIClosedRCReadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CIClosedRCReadType" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIClosedRCReadType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfCIClosedRCReadType", propOrder = {
    "ciClosedRCReadType"
})
public class ArrayOfCIClosedRCReadType {

    @XmlElement(name = "CIClosedRCReadType", nillable = true)
    protected List<CIClosedRCReadType> ciClosedRCReadType;

    /**
     * Gets the value of the ciClosedRCReadType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ciClosedRCReadType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCIClosedRCReadType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CIClosedRCReadType }
     * 
     * 
     */
    public List<CIClosedRCReadType> getCIClosedRCReadType() {
        if (ciClosedRCReadType == null) {
            ciClosedRCReadType = new ArrayList<CIClosedRCReadType>();
        }
        return this.ciClosedRCReadType;
    }

}
