//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.01 at 04:50:33 PM IST 
//


package com.koopid.ccmm.wsdl.ci_contact;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIActionSource.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CIActionSource"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Not_Available"/&gt;
 *     &lt;enumeration value="Automated_Response"/&gt;
 *     &lt;enumeration value="EMail_from_Customer"/&gt;
 *     &lt;enumeration value="EMail_from_Agent_to_Customer"/&gt;
 *     &lt;enumeration value="Phone_from_Customer"/&gt;
 *     &lt;enumeration value="Phone_from_Agent_to_Customer"/&gt;
 *     &lt;enumeration value="Text_Chat_from_Customer"/&gt;
 *     &lt;enumeration value="Text_Chat_from_Agent_to_Customer"/&gt;
 *     &lt;enumeration value="Other_from_Customer"/&gt;
 *     &lt;enumeration value="Other_from_Agent_to_Customer"/&gt;
 *     &lt;enumeration value="Transfer_to_Agent"/&gt;
 *     &lt;enumeration value="Transfer_to_Skillset"/&gt;
 *     &lt;enumeration value="Transfer_to_External_Agent"/&gt;
 *     &lt;enumeration value="Agent_Created_Contact"/&gt;
 *     &lt;enumeration value="Agent_Created"/&gt;
 *     &lt;enumeration value="Callback_Request_from_Customer"/&gt;
 *     &lt;enumeration value="Password_Reminder_to_Customer"/&gt;
 *     &lt;enumeration value="Outbound_Voice_Call_Not_Made"/&gt;
 *     &lt;enumeration value="Supervisor_Closed"/&gt;
 *     &lt;enumeration value="Customer_Abandoned_WebOnHold"/&gt;
 *     &lt;enumeration value="Closed_By_Custom_Application"/&gt;
 *     &lt;enumeration value="Chat_Text_History"/&gt;
 *     &lt;enumeration value="Unspecified"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CIActionSource5")
@XmlEnum
public enum CIActionSource {

    @XmlEnumValue("Not_Available")
    NOT_AVAILABLE("Not_Available"),
    @XmlEnumValue("Automated_Response")
    AUTOMATED_RESPONSE("Automated_Response"),
    @XmlEnumValue("EMail_from_Customer")
    E_MAIL_FROM_CUSTOMER("EMail_from_Customer"),
    @XmlEnumValue("EMail_from_Agent_to_Customer")
    E_MAIL_FROM_AGENT_TO_CUSTOMER("EMail_from_Agent_to_Customer"),
    @XmlEnumValue("Phone_from_Customer")
    PHONE_FROM_CUSTOMER("Phone_from_Customer"),
    @XmlEnumValue("Phone_from_Agent_to_Customer")
    PHONE_FROM_AGENT_TO_CUSTOMER("Phone_from_Agent_to_Customer"),
    @XmlEnumValue("Text_Chat_from_Customer")
    TEXT_CHAT_FROM_CUSTOMER("Text_Chat_from_Customer"),
    @XmlEnumValue("Text_Chat_from_Agent_to_Customer")
    TEXT_CHAT_FROM_AGENT_TO_CUSTOMER("Text_Chat_from_Agent_to_Customer"),
    @XmlEnumValue("Other_from_Customer")
    OTHER_FROM_CUSTOMER("Other_from_Customer"),
    @XmlEnumValue("Other_from_Agent_to_Customer")
    OTHER_FROM_AGENT_TO_CUSTOMER("Other_from_Agent_to_Customer"),
    @XmlEnumValue("Transfer_to_Agent")
    TRANSFER_TO_AGENT("Transfer_to_Agent"),
    @XmlEnumValue("Transfer_to_Skillset")
    TRANSFER_TO_SKILLSET("Transfer_to_Skillset"),
    @XmlEnumValue("Transfer_to_External_Agent")
    TRANSFER_TO_EXTERNAL_AGENT("Transfer_to_External_Agent"),
    @XmlEnumValue("Agent_Created_Contact")
    AGENT_CREATED_CONTACT("Agent_Created_Contact"),
    @XmlEnumValue("Agent_Created")
    AGENT_CREATED("Agent_Created"),
    @XmlEnumValue("Callback_Request_from_Customer")
    CALLBACK_REQUEST_FROM_CUSTOMER("Callback_Request_from_Customer"),
    @XmlEnumValue("Password_Reminder_to_Customer")
    PASSWORD_REMINDER_TO_CUSTOMER("Password_Reminder_to_Customer"),
    @XmlEnumValue("Outbound_Voice_Call_Not_Made")
    OUTBOUND_VOICE_CALL_NOT_MADE("Outbound_Voice_Call_Not_Made"),
    @XmlEnumValue("Supervisor_Closed")
    SUPERVISOR_CLOSED("Supervisor_Closed"),
    @XmlEnumValue("Customer_Abandoned_WebOnHold")
    CUSTOMER_ABANDONED_WEB_ON_HOLD("Customer_Abandoned_WebOnHold"),
    @XmlEnumValue("Closed_By_Custom_Application")
    CLOSED_BY_CUSTOM_APPLICATION("Closed_By_Custom_Application"),
    @XmlEnumValue("Chat_Text_History")
    CHAT_TEXT_HISTORY("Chat_Text_History"),
    @XmlEnumValue("Unspecified")
    UNSPECIFIED("Unspecified");
    private final String value;

    CIActionSource(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CIActionSource fromValue(String v) {
        for (CIActionSource c: CIActionSource.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
