//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.01 at 04:50:33 PM IST 
//


package com.koopid.ccmm.wsdl.ci_contact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="contactID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="closureText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="closedReasonCodeValue" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="closedReasonCodeSpecified" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="sessionKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactID",
    "closureText",
    "closedReasonCodeValue",
    "closedReasonCodeSpecified",
    "sessionKey"
})
@XmlRootElement(name = "CloseContact", namespace = "http://webservices.ci.ccmm.applications.nortel.com")
public class CloseContact {

    @XmlElement(namespace = "http://webservices.ci.ccmm.applications.nortel.com")
    protected long contactID;
    @XmlElement(namespace = "http://webservices.ci.ccmm.applications.nortel.com")
    protected String closureText;
    @XmlElement(namespace = "http://webservices.ci.ccmm.applications.nortel.com")
    protected long closedReasonCodeValue;
    @XmlElement(namespace = "http://webservices.ci.ccmm.applications.nortel.com")
    protected boolean closedReasonCodeSpecified;
    @XmlElement(namespace = "http://webservices.ci.ccmm.applications.nortel.com")
    protected String sessionKey;

    /**
     * Gets the value of the contactID property.
     * 
     */
    public long getContactID() {
        return contactID;
    }

    /**
     * Sets the value of the contactID property.
     * 
     */
    public void setContactID(long value) {
        this.contactID = value;
    }

    /**
     * Gets the value of the closureText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosureText() {
        return closureText;
    }

    /**
     * Sets the value of the closureText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosureText(String value) {
        this.closureText = value;
    }

    /**
     * Gets the value of the closedReasonCodeValue property.
     * 
     */
    public long getClosedReasonCodeValue() {
        return closedReasonCodeValue;
    }

    /**
     * Sets the value of the closedReasonCodeValue property.
     * 
     */
    public void setClosedReasonCodeValue(long value) {
        this.closedReasonCodeValue = value;
    }

    /**
     * Gets the value of the closedReasonCodeSpecified property.
     * 
     */
    public boolean isClosedReasonCodeSpecified() {
        return closedReasonCodeSpecified;
    }

    /**
     * Sets the value of the closedReasonCodeSpecified property.
     * 
     */
    public void setClosedReasonCodeSpecified(boolean value) {
        this.closedReasonCodeSpecified = value;
    }

    /**
     * Gets the value of the sessionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * Sets the value of the sessionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionKey(String value) {
        this.sessionKey = value;
    }

}
