//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.01 at 04:50:33 PM IST 
//


package com.koopid.ccmm.wsdl.ci_contact;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetClosedReasonCodeByNameResult" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIClosedRCReadType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getClosedReasonCodeByNameResult"
})
@XmlRootElement(name = "GetClosedReasonCodeByNameResponse", namespace = "http://webservices.ci.ccmm.applications.nortel.com")
public class GetClosedReasonCodeByNameResponse {

    @XmlElement(name = "GetClosedReasonCodeByNameResult", namespace = "http://webservices.ci.ccmm.applications.nortel.com")
    protected CIClosedRCReadType getClosedReasonCodeByNameResult;

    /**
     * Gets the value of the getClosedReasonCodeByNameResult property.
     * 
     * @return
     *     possible object is
     *     {@link CIClosedRCReadType }
     *     
     */
    public CIClosedRCReadType getGetClosedReasonCodeByNameResult() {
        return getClosedReasonCodeByNameResult;
    }

    /**
     * Sets the value of the getClosedReasonCodeByNameResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIClosedRCReadType }
     *     
     */
    public void setGetClosedReasonCodeByNameResult(CIClosedRCReadType value) {
        this.getClosedReasonCodeByNameResult = value;
    }

}
