//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.01 at 04:50:33 PM IST 
//


package com.koopid.ccmm.wsdl.ci_contact;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koopid.ccmm.wsdl.ci_contact package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koopid.ccmm.wsdl.ci_contact
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadContact }
     * 
     */
    public ReadContact createReadContact() {
        return new ReadContact();
    }

    /**
     * Create an instance of {@link ReadContactResponse }
     * 
     */
    public ReadContactResponse createReadContactResponse() {
        return new ReadContactResponse();
    }

    /**
     * Create an instance of {@link CIContactReadType }
     * 
     */
    public CIContactReadType createCIContactReadType() {
        return new CIContactReadType();
    }

    /**
     * Create an instance of {@link CloseContact }
     * 
     */
    public CloseContact createCloseContact() {
        return new CloseContact();
    }

    /**
     * Create an instance of {@link CloseContactResponse }
     * 
     */
    public CloseContactResponse createCloseContactResponse() {
        return new CloseContactResponse();
    }

    /**
     * Create an instance of {@link GetAllClosedReasonCodes }
     * 
     */
    public GetAllClosedReasonCodes createGetAllClosedReasonCodes() {
        return new GetAllClosedReasonCodes();
    }

    /**
     * Create an instance of {@link GetAllClosedReasonCodesResponse }
     * 
     */
    public GetAllClosedReasonCodesResponse createGetAllClosedReasonCodesResponse() {
        return new GetAllClosedReasonCodesResponse();
    }

    /**
     * Create an instance of {@link CIMultipleClosedRCReadType }
     * 
     */
    public CIMultipleClosedRCReadType createCIMultipleClosedRCReadType() {
        return new CIMultipleClosedRCReadType();
    }

    /**
     * Create an instance of {@link GetClosedReasonCodeByName }
     * 
     */
    public GetClosedReasonCodeByName createGetClosedReasonCodeByName() {
        return new GetClosedReasonCodeByName();
    }

    /**
     * Create an instance of {@link GetClosedReasonCodeByNameResponse }
     * 
     */
    public GetClosedReasonCodeByNameResponse createGetClosedReasonCodeByNameResponse() {
        return new GetClosedReasonCodeByNameResponse();
    }

    /**
     * Create an instance of {@link CIClosedRCReadType }
     * 
     */
    public CIClosedRCReadType createCIClosedRCReadType() {
        return new CIClosedRCReadType();
    }

    /**
     * Create an instance of {@link CISkillsetReadType }
     * 
     */
    public CISkillsetReadType createCISkillsetReadType() {
        return new CISkillsetReadType();
    }

    /**
     * Create an instance of {@link CIDateTime }
     * 
     */
    public CIDateTime createCIDateTime() {
        return new CIDateTime();
    }

    /**
     * Create an instance of {@link CIAgentReadType }
     * 
     */
    public CIAgentReadType createCIAgentReadType() {
        return new CIAgentReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIActionReadType }
     * 
     */
    public ArrayOfCIActionReadType createArrayOfCIActionReadType() {
        return new ArrayOfCIActionReadType();
    }

    /**
     * Create an instance of {@link CIActionReadType }
     * 
     */
    public CIActionReadType createCIActionReadType() {
        return new CIActionReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCICustomFieldReadType }
     * 
     */
    public ArrayOfCICustomFieldReadType createArrayOfCICustomFieldReadType() {
        return new ArrayOfCICustomFieldReadType();
    }

    /**
     * Create an instance of {@link CICustomFieldReadType }
     * 
     */
    public CICustomFieldReadType createCICustomFieldReadType() {
        return new CICustomFieldReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIClosedRCReadType }
     * 
     */
    public ArrayOfCIClosedRCReadType createArrayOfCIClosedRCReadType() {
        return new ArrayOfCIClosedRCReadType();
    }

}
