//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:08:42 PM IST 
//


package com.koopid.ccmm.wsdl.ci_webcomm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIChatMessageReadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIChatMessageReadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="chatMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="hiddenMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="writeTime" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIDateTime" minOccurs="0"/&gt;
 *         &lt;element name="chatMessageType" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIChatMessageType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIChatMessageReadType", namespace = "http://datatypes.ci.ccmm.applications.nortel.com", propOrder = {
    "chatMessage",
    "hiddenMessage",
    "writeTime",
    "chatMessageType"
})
public class CIChatMessageReadType {

    protected String chatMessage;
    protected String hiddenMessage;
    protected CIDateTime writeTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CIChatMessageType chatMessageType;

    /**
     * Gets the value of the chatMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChatMessage() {
        return chatMessage;
    }

    /**
     * Sets the value of the chatMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChatMessage(String value) {
        this.chatMessage = value;
    }

    /**
     * Gets the value of the hiddenMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHiddenMessage() {
        return hiddenMessage;
    }

    /**
     * Sets the value of the hiddenMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHiddenMessage(String value) {
        this.hiddenMessage = value;
    }

    /**
     * Gets the value of the writeTime property.
     * 
     * @return
     *     possible object is
     *     {@link CIDateTime }
     *     
     */
    public CIDateTime getWriteTime() {
        return writeTime;
    }

    /**
     * Sets the value of the writeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIDateTime }
     *     
     */
    public void setWriteTime(CIDateTime value) {
        this.writeTime = value;
    }

    /**
     * Gets the value of the chatMessageType property.
     * 
     * @return
     *     possible object is
     *     {@link CIChatMessageType }
     *     
     */
    public CIChatMessageType getChatMessageType() {
        return chatMessageType;
    }

    /**
     * Sets the value of the chatMessageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIChatMessageType }
     *     
     */
    public void setChatMessageType(CIChatMessageType value) {
        this.chatMessageType = value;
    }

}
