//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:08:42 PM IST 
//


package com.koopid.ccmm.wsdl.ci_webcomm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIMultipleChatMessageReadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIMultipleChatMessageReadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="listOfChatMessages" type="{http://datatypes.ci.ccmm.applications.nortel.com}ArrayOfCIChatMessageReadType" minOccurs="0"/&gt;
 *         &lt;element name="isWriting" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="lastReadTime" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIDateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIMultipleChatMessageReadType", namespace = "http://datatypes.ci.ccmm.applications.nortel.com", propOrder = {
    "listOfChatMessages",
    "isWriting",
    "lastReadTime"
})
public class CIMultipleChatMessageReadType {

    protected ArrayOfCIChatMessageReadType listOfChatMessages;
    protected boolean isWriting;
    protected CIDateTime lastReadTime;

    /**
     * Gets the value of the listOfChatMessages property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCIChatMessageReadType }
     *     
     */
    public ArrayOfCIChatMessageReadType getListOfChatMessages() {
        return listOfChatMessages;
    }

    /**
     * Sets the value of the listOfChatMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCIChatMessageReadType }
     *     
     */
    public void setListOfChatMessages(ArrayOfCIChatMessageReadType value) {
        this.listOfChatMessages = value;
    }

    /**
     * Gets the value of the isWriting property.
     * 
     */
    public boolean isIsWriting() {
        return isWriting;
    }

    /**
     * Sets the value of the isWriting property.
     * 
     */
    public void setIsWriting(boolean value) {
        this.isWriting = value;
    }

    /**
     * Gets the value of the lastReadTime property.
     * 
     * @return
     *     possible object is
     *     {@link CIDateTime }
     *     
     */
    public CIDateTime getLastReadTime() {
        return lastReadTime;
    }

    /**
     * Sets the value of the lastReadTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIDateTime }
     *     
     */
    public void setLastReadTime(CIDateTime value) {
        this.lastReadTime = value;
    }

}
