//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:08:42 PM IST 
//


package com.koopid.ccmm.wsdl.ci_webcomm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koopid.ccmm.wsdl.ci_webcomm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koopid.ccmm.wsdl.ci_webcomm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateWebCommsSession }
     * 
     */
    public CreateWebCommsSession createCreateWebCommsSession() {
        return new CreateWebCommsSession();
    }

    /**
     * Create an instance of {@link CreateWebCommsSessionResponse }
     * 
     */
    public CreateWebCommsSessionResponse createCreateWebCommsSessionResponse() {
        return new CreateWebCommsSessionResponse();
    }

    /**
     * Create an instance of {@link WriteChatMessage }
     * 
     */
    public WriteChatMessage createWriteChatMessage() {
        return new WriteChatMessage();
    }

    /**
     * Create an instance of {@link WriteChatMessageResponse }
     * 
     */
    public WriteChatMessageResponse createWriteChatMessageResponse() {
        return new WriteChatMessageResponse();
    }

    /**
     * Create an instance of {@link ReadChatMessage }
     * 
     */
    public ReadChatMessage createReadChatMessage() {
        return new ReadChatMessage();
    }

    /**
     * Create an instance of {@link CIDateTime }
     * 
     */
    public CIDateTime createCIDateTime() {
        return new CIDateTime();
    }

    /**
     * Create an instance of {@link ReadChatMessageResponse }
     * 
     */
    public ReadChatMessageResponse createReadChatMessageResponse() {
        return new ReadChatMessageResponse();
    }

    /**
     * Create an instance of {@link CIMultipleChatMessageReadType }
     * 
     */
    public CIMultipleChatMessageReadType createCIMultipleChatMessageReadType() {
        return new CIMultipleChatMessageReadType();
    }

    /**
     * Create an instance of {@link RequestChatHistory }
     * 
     */
    public RequestChatHistory createRequestChatHistory() {
        return new RequestChatHistory();
    }

    /**
     * Create an instance of {@link RequestChatHistoryResponse }
     * 
     */
    public RequestChatHistoryResponse createRequestChatHistoryResponse() {
        return new RequestChatHistoryResponse();
    }

    /**
     * Create an instance of {@link GetWebOnHoldURLs }
     * 
     */
    public GetWebOnHoldURLs createGetWebOnHoldURLs() {
        return new GetWebOnHoldURLs();
    }

    /**
     * Create an instance of {@link GetWebOnHoldURLsResponse }
     * 
     */
    public GetWebOnHoldURLsResponse createGetWebOnHoldURLsResponse() {
        return new GetWebOnHoldURLsResponse();
    }

    /**
     * Create an instance of {@link CIMultipleOnHoldURLReadType }
     * 
     */
    public CIMultipleOnHoldURLReadType createCIMultipleOnHoldURLReadType() {
        return new CIMultipleOnHoldURLReadType();
    }

    /**
     * Create an instance of {@link UpdateAliveTime }
     * 
     */
    public UpdateAliveTime createUpdateAliveTime() {
        return new UpdateAliveTime();
    }

    /**
     * Create an instance of {@link UpdateAliveTimeResponse }
     * 
     */
    public UpdateAliveTimeResponse createUpdateAliveTimeResponse() {
        return new UpdateAliveTimeResponse();
    }

    /**
     * Create an instance of {@link UpdateAliveTimeAndUpdateIsTyping }
     * 
     */
    public UpdateAliveTimeAndUpdateIsTyping createUpdateAliveTimeAndUpdateIsTyping() {
        return new UpdateAliveTimeAndUpdateIsTyping();
    }

    /**
     * Create an instance of {@link UpdateAliveTimeAndUpdateIsTypingResponse }
     * 
     */
    public UpdateAliveTimeAndUpdateIsTypingResponse createUpdateAliveTimeAndUpdateIsTypingResponse() {
        return new UpdateAliveTimeAndUpdateIsTypingResponse();
    }

    /**
     * Create an instance of {@link AbandonQueuingWebCommsContact }
     * 
     */
    public AbandonQueuingWebCommsContact createAbandonQueuingWebCommsContact() {
        return new AbandonQueuingWebCommsContact();
    }

    /**
     * Create an instance of {@link AbandonQueuingWebCommsContactResponse }
     * 
     */
    public AbandonQueuingWebCommsContactResponse createAbandonQueuingWebCommsContactResponse() {
        return new AbandonQueuingWebCommsContactResponse();
    }

    /**
     * Create an instance of {@link AbandonQueuingWCContact }
     * 
     */
    public AbandonQueuingWCContact createAbandonQueuingWCContact() {
        return new AbandonQueuingWCContact();
    }

    /**
     * Create an instance of {@link AbandonQueuingWCContactResponse }
     * 
     */
    public AbandonQueuingWCContactResponse createAbandonQueuingWCContactResponse() {
        return new AbandonQueuingWCContactResponse();
    }

    /**
     * Create an instance of {@link GetCustomerTextChatLabel }
     * 
     */
    public GetCustomerTextChatLabel createGetCustomerTextChatLabel() {
        return new GetCustomerTextChatLabel();
    }

    /**
     * Create an instance of {@link GetCustomerTextChatLabelResponse }
     * 
     */
    public GetCustomerTextChatLabelResponse createGetCustomerTextChatLabelResponse() {
        return new GetCustomerTextChatLabelResponse();
    }

    /**
     * Create an instance of {@link GetCustomerTextChatName }
     * 
     */
    public GetCustomerTextChatName createGetCustomerTextChatName() {
        return new GetCustomerTextChatName();
    }

    /**
     * Create an instance of {@link GetCustomerTextChatNameResponse }
     * 
     */
    public GetCustomerTextChatNameResponse createGetCustomerTextChatNameResponse() {
        return new GetCustomerTextChatNameResponse();
    }

    /**
     * Create an instance of {@link CICustomerChatNameReadType }
     * 
     */
    public CICustomerChatNameReadType createCICustomerChatNameReadType() {
        return new CICustomerChatNameReadType();
    }

    /**
     * Create an instance of {@link GetTrunkAccessCode }
     * 
     */
    public GetTrunkAccessCode createGetTrunkAccessCode() {
        return new GetTrunkAccessCode();
    }

    /**
     * Create an instance of {@link GetTrunkAccessCodeResponse }
     * 
     */
    public GetTrunkAccessCodeResponse createGetTrunkAccessCodeResponse() {
        return new GetTrunkAccessCodeResponse();
    }

    /**
     * Create an instance of {@link GetContactOnHoldMessages }
     * 
     */
    public GetContactOnHoldMessages createGetContactOnHoldMessages() {
        return new GetContactOnHoldMessages();
    }

    /**
     * Create an instance of {@link GetContactOnHoldMessagesResponse }
     * 
     */
    public GetContactOnHoldMessagesResponse createGetContactOnHoldMessagesResponse() {
        return new GetContactOnHoldMessagesResponse();
    }

    /**
     * Create an instance of {@link CIMultipleOnHoldMessages }
     * 
     */
    public CIMultipleOnHoldMessages createCIMultipleOnHoldMessages() {
        return new CIMultipleOnHoldMessages();
    }

    /**
     * Create an instance of {@link ArrayOfCIChatMessageReadType }
     * 
     */
    public ArrayOfCIChatMessageReadType createArrayOfCIChatMessageReadType() {
        return new ArrayOfCIChatMessageReadType();
    }

    /**
     * Create an instance of {@link CIChatMessageReadType }
     * 
     */
    public CIChatMessageReadType createCIChatMessageReadType() {
        return new CIChatMessageReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIOnHoldURLReadType }
     * 
     */
    public ArrayOfCIOnHoldURLReadType createArrayOfCIOnHoldURLReadType() {
        return new ArrayOfCIOnHoldURLReadType();
    }

    /**
     * Create an instance of {@link CIOnHoldURLReadType }
     * 
     */
    public CIOnHoldURLReadType createCIOnHoldURLReadType() {
        return new CIOnHoldURLReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCICOnHoldMessages }
     * 
     */
    public ArrayOfCICOnHoldMessages createArrayOfCICOnHoldMessages() {
        return new ArrayOfCICOnHoldMessages();
    }

    /**
     * Create an instance of {@link CICOnHoldMessages }
     * 
     */
    public CICOnHoldMessages createCICOnHoldMessages() {
        return new CICOnHoldMessages();
    }

}
