//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:04:16 PM IST 
//


package com.koopid.ccmm.wsdl.ci_utility;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetTotalQueuedToSkillsetResult" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getTotalQueuedToSkillsetResult"
})
@XmlRootElement(name = "GetTotalQueuedToSkillsetResponse")
public class GetTotalQueuedToSkillsetResponse {

    @XmlElement(name = "GetTotalQueuedToSkillsetResult")
    protected long getTotalQueuedToSkillsetResult;

    /**
     * Gets the value of the getTotalQueuedToSkillsetResult property.
     * 
     */
    public long getGetTotalQueuedToSkillsetResult() {
        return getTotalQueuedToSkillsetResult;
    }

    /**
     * Sets the value of the getTotalQueuedToSkillsetResult property.
     * 
     */
    public void setGetTotalQueuedToSkillsetResult(long value) {
        this.getTotalQueuedToSkillsetResult = value;
    }

}
