//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:04:16 PM IST 
//


package com.koopid.ccmm.wsdl.ci_utility;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koopid.ccmm.wsdl.ci_utility package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koopid.ccmm.wsdl.ci_utility
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerLogin }
     * 
     */
    public CustomerLogin createCustomerLogin() {
        return new CustomerLogin();
    }

    /**
     * Create an instance of {@link CustomerLoginResponse }
     * 
     */
    public CustomerLoginResponse createCustomerLoginResponse() {
        return new CustomerLoginResponse();
    }

    /**
     * Create an instance of {@link GetAnonymousSessionKey }
     * 
     */
    public GetAnonymousSessionKey createGetAnonymousSessionKey() {
        return new GetAnonymousSessionKey();
    }

    /**
     * Create an instance of {@link GetAnonymousSessionKeyResponse }
     * 
     */
    public GetAnonymousSessionKeyResponse createGetAnonymousSessionKeyResponse() {
        return new GetAnonymousSessionKeyResponse();
    }

    /**
     * Create an instance of {@link AnonymousLoginResult }
     * 
     */
    public AnonymousLoginResult createAnonymousLoginResult() {
        return new AnonymousLoginResult();
    }

    /**
     * Create an instance of {@link GetAnonymousCustomerID }
     * 
     */
    public GetAnonymousCustomerID createGetAnonymousCustomerID() {
        return new GetAnonymousCustomerID();
    }

    /**
     * Create an instance of {@link GetAnonymousCustomerIDResponse }
     * 
     */
    public GetAnonymousCustomerIDResponse createGetAnonymousCustomerIDResponse() {
        return new GetAnonymousCustomerIDResponse();
    }

    /**
     * Create an instance of {@link GetAndUpdateAnonymousCustomerID }
     * 
     */
    public GetAndUpdateAnonymousCustomerID createGetAndUpdateAnonymousCustomerID() {
        return new GetAndUpdateAnonymousCustomerID();
    }

    /**
     * Create an instance of {@link CICustomerReadType }
     * 
     */
    public CICustomerReadType createCICustomerReadType() {
        return new CICustomerReadType();
    }

    /**
     * Create an instance of {@link GetAndUpdateAnonymousCustomerIDResponse }
     * 
     */
    public GetAndUpdateAnonymousCustomerIDResponse createGetAndUpdateAnonymousCustomerIDResponse() {
        return new GetAndUpdateAnonymousCustomerIDResponse();
    }

    /**
     * Create an instance of {@link ExtendedCustomerLogin }
     * 
     */
    public ExtendedCustomerLogin createExtendedCustomerLogin() {
        return new ExtendedCustomerLogin();
    }

    /**
     * Create an instance of {@link ExtendedCustomerLoginResponse }
     * 
     */
    public ExtendedCustomerLoginResponse createExtendedCustomerLoginResponse() {
        return new ExtendedCustomerLoginResponse();
    }

    /**
     * Create an instance of {@link CustomerLogoff }
     * 
     */
    public CustomerLogoff createCustomerLogoff() {
        return new CustomerLogoff();
    }

    /**
     * Create an instance of {@link CustomerLogoffResponse }
     * 
     */
    public CustomerLogoffResponse createCustomerLogoffResponse() {
        return new CustomerLogoffResponse();
    }

    /**
     * Create an instance of {@link CustomerEndSession }
     * 
     */
    public CustomerEndSession createCustomerEndSession() {
        return new CustomerEndSession();
    }

    /**
     * Create an instance of {@link CustomerEndSessionResponse }
     * 
     */
    public CustomerEndSessionResponse createCustomerEndSessionResponse() {
        return new CustomerEndSessionResponse();
    }

    /**
     * Create an instance of {@link CustomerLogoffByContactID }
     * 
     */
    public CustomerLogoffByContactID createCustomerLogoffByContactID() {
        return new CustomerLogoffByContactID();
    }

    /**
     * Create an instance of {@link CustomerLogoffByContactIDResponse }
     * 
     */
    public CustomerLogoffByContactIDResponse createCustomerLogoffByContactIDResponse() {
        return new CustomerLogoffByContactIDResponse();
    }

    /**
     * Create an instance of {@link AdministratorLogin }
     * 
     */
    public AdministratorLogin createAdministratorLogin() {
        return new AdministratorLogin();
    }

    /**
     * Create an instance of {@link AdministratorLoginResponse }
     * 
     */
    public AdministratorLoginResponse createAdministratorLoginResponse() {
        return new AdministratorLoginResponse();
    }

    /**
     * Create an instance of {@link AdministratorLogoff }
     * 
     */
    public AdministratorLogoff createAdministratorLogoff() {
        return new AdministratorLogoff();
    }

    /**
     * Create an instance of {@link AdministratorLogoffResponse }
     * 
     */
    public AdministratorLogoffResponse createAdministratorLogoffResponse() {
        return new AdministratorLogoffResponse();
    }

    /**
     * Create an instance of {@link IsContactCentreClosed }
     * 
     */
    public IsContactCentreClosed createIsContactCentreClosed() {
        return new IsContactCentreClosed();
    }

    /**
     * Create an instance of {@link IsContactCentreClosedResponse }
     * 
     */
    public IsContactCentreClosedResponse createIsContactCentreClosedResponse() {
        return new IsContactCentreClosedResponse();
    }

    /**
     * Create an instance of {@link GetServerTime }
     * 
     */
    public GetServerTime createGetServerTime() {
        return new GetServerTime();
    }

    /**
     * Create an instance of {@link GetServerTimeResponse }
     * 
     */
    public GetServerTimeResponse createGetServerTimeResponse() {
        return new GetServerTimeResponse();
    }

    /**
     * Create an instance of {@link CIDateTime }
     * 
     */
    public CIDateTime createCIDateTime() {
        return new CIDateTime();
    }

    /**
     * Create an instance of {@link GetServerUTCTime }
     * 
     */
    public GetServerUTCTime createGetServerUTCTime() {
        return new GetServerUTCTime();
    }

    /**
     * Create an instance of {@link GetServerUTCTimeResponse }
     * 
     */
    public GetServerUTCTimeResponse createGetServerUTCTimeResponse() {
        return new GetServerUTCTimeResponse();
    }

    /**
     * Create an instance of {@link GetServerRAWTime }
     * 
     */
    public GetServerRAWTime createGetServerRAWTime() {
        return new GetServerRAWTime();
    }

    /**
     * Create an instance of {@link GetServerRAWTimeResponse }
     * 
     */
    public GetServerRAWTimeResponse createGetServerRAWTimeResponse() {
        return new GetServerRAWTimeResponse();
    }

    /**
     * Create an instance of {@link TimeStampToMilliseconds }
     * 
     */
    public TimeStampToMilliseconds createTimeStampToMilliseconds() {
        return new TimeStampToMilliseconds();
    }

    /**
     * Create an instance of {@link CITimeStamp }
     * 
     */
    public CITimeStamp createCITimeStamp() {
        return new CITimeStamp();
    }

    /**
     * Create an instance of {@link TimeStampToMillisecondsResponse }
     * 
     */
    public TimeStampToMillisecondsResponse createTimeStampToMillisecondsResponse() {
        return new TimeStampToMillisecondsResponse();
    }

    /**
     * Create an instance of {@link MillisecondsToTimeStamp }
     * 
     */
    public MillisecondsToTimeStamp createMillisecondsToTimeStamp() {
        return new MillisecondsToTimeStamp();
    }

    /**
     * Create an instance of {@link MillisecondsToTimeStampResponse }
     * 
     */
    public MillisecondsToTimeStampResponse createMillisecondsToTimeStampResponse() {
        return new MillisecondsToTimeStampResponse();
    }

    /**
     * Create an instance of {@link GetTotalQueued }
     * 
     */
    public GetTotalQueued createGetTotalQueued() {
        return new GetTotalQueued();
    }

    /**
     * Create an instance of {@link GetTotalQueuedResponse }
     * 
     */
    public GetTotalQueuedResponse createGetTotalQueuedResponse() {
        return new GetTotalQueuedResponse();
    }

    /**
     * Create an instance of {@link GetTotalQueuedToSkillset }
     * 
     */
    public GetTotalQueuedToSkillset createGetTotalQueuedToSkillset() {
        return new GetTotalQueuedToSkillset();
    }

    /**
     * Create an instance of {@link GetTotalQueuedToSkillsetResponse }
     * 
     */
    public GetTotalQueuedToSkillsetResponse createGetTotalQueuedToSkillsetResponse() {
        return new GetTotalQueuedToSkillsetResponse();
    }

    /**
     * Create an instance of {@link ArrayOfCIAddressReadType }
     * 
     */
    public ArrayOfCIAddressReadType createArrayOfCIAddressReadType() {
        return new ArrayOfCIAddressReadType();
    }

    /**
     * Create an instance of {@link CIAddressReadType }
     * 
     */
    public CIAddressReadType createCIAddressReadType() {
        return new CIAddressReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIPhoneNumberReadType }
     * 
     */
    public ArrayOfCIPhoneNumberReadType createArrayOfCIPhoneNumberReadType() {
        return new ArrayOfCIPhoneNumberReadType();
    }

    /**
     * Create an instance of {@link CIPhoneNumberReadType }
     * 
     */
    public CIPhoneNumberReadType createCIPhoneNumberReadType() {
        return new CIPhoneNumberReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIEmailAddressReadType }
     * 
     */
    public ArrayOfCIEmailAddressReadType createArrayOfCIEmailAddressReadType() {
        return new ArrayOfCIEmailAddressReadType();
    }

    /**
     * Create an instance of {@link CIEmailAddressReadType }
     * 
     */
    public CIEmailAddressReadType createCIEmailAddressReadType() {
        return new CIEmailAddressReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCICustomFieldReadType }
     * 
     */
    public ArrayOfCICustomFieldReadType createArrayOfCICustomFieldReadType() {
        return new ArrayOfCICustomFieldReadType();
    }

    /**
     * Create an instance of {@link CICustomFieldReadType }
     * 
     */
    public CICustomFieldReadType createCICustomFieldReadType() {
        return new CICustomFieldReadType();
    }

}
