//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.10 at 07:33:58 PM IST 
//


package com.koopid.ccmm.wsdl.ci_skill_set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIMultipleSkillsetsReadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIMultipleSkillsetsReadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="skillsetList" type="{http://datatypes.ci.ccmm.applications.nortel.com}ArrayOfCISkillsetReadType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIMultipleSkillsetsReadType", namespace = "http://datatypes.ci.ccmm.applications.nortel.com", propOrder = {
    "skillsetList"
})
public class CIMultipleSkillsetsReadType {

    protected ArrayOfCISkillsetReadType skillsetList;

    /**
     * Gets the value of the skillsetList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCISkillsetReadType }
     *     
     */
    public ArrayOfCISkillsetReadType getSkillsetList() {
        return skillsetList;
    }

    /**
     * Sets the value of the skillsetList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCISkillsetReadType }
     *     
     */
    public void setSkillsetList(ArrayOfCISkillsetReadType value) {
        this.skillsetList = value;
    }

}
