//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.10 at 07:33:58 PM IST 
//


package com.koopid.ccmm.wsdl.ci_skill_set;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koopid.ccmm.wsdl.ci_skill_set package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koopid.ccmm.wsdl.ci_skill_set
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllSkillsets }
     * 
     */
    public GetAllSkillsets createGetAllSkillsets() {
        return new GetAllSkillsets();
    }

    /**
     * Create an instance of {@link GetAllSkillsetsResponse }
     * 
     */
    public GetAllSkillsetsResponse createGetAllSkillsetsResponse() {
        return new GetAllSkillsetsResponse();
    }

    /**
     * Create an instance of {@link CIMultipleSkillsetsReadType }
     * 
     */
    public CIMultipleSkillsetsReadType createCIMultipleSkillsetsReadType() {
        return new CIMultipleSkillsetsReadType();
    }

    /**
     * Create an instance of {@link GetAllWebSkillsets }
     * 
     */
    public GetAllWebSkillsets createGetAllWebSkillsets() {
        return new GetAllWebSkillsets();
    }

    /**
     * Create an instance of {@link GetAllWebSkillsetsResponse }
     * 
     */
    public GetAllWebSkillsetsResponse createGetAllWebSkillsetsResponse() {
        return new GetAllWebSkillsetsResponse();
    }

    /**
     * Create an instance of {@link GetAllOutboundSkillsets }
     * 
     */
    public GetAllOutboundSkillsets createGetAllOutboundSkillsets() {
        return new GetAllOutboundSkillsets();
    }

    /**
     * Create an instance of {@link GetAllOutboundSkillsetsResponse }
     * 
     */
    public GetAllOutboundSkillsetsResponse createGetAllOutboundSkillsetsResponse() {
        return new GetAllOutboundSkillsetsResponse();
    }

    /**
     * Create an instance of {@link GetAllEmailSkillsets }
     * 
     */
    public GetAllEmailSkillsets createGetAllEmailSkillsets() {
        return new GetAllEmailSkillsets();
    }

    /**
     * Create an instance of {@link GetAllEmailSkillsetsResponse }
     * 
     */
    public GetAllEmailSkillsetsResponse createGetAllEmailSkillsetsResponse() {
        return new GetAllEmailSkillsetsResponse();
    }

    /**
     * Create an instance of {@link GetSkillsetByID }
     * 
     */
    public GetSkillsetByID createGetSkillsetByID() {
        return new GetSkillsetByID();
    }

    /**
     * Create an instance of {@link GetSkillsetByIDResponse }
     * 
     */
    public GetSkillsetByIDResponse createGetSkillsetByIDResponse() {
        return new GetSkillsetByIDResponse();
    }

    /**
     * Create an instance of {@link CISkillsetReadType }
     * 
     */
    public CISkillsetReadType createCISkillsetReadType() {
        return new CISkillsetReadType();
    }

    /**
     * Create an instance of {@link GetSkillsetByName }
     * 
     */
    public GetSkillsetByName createGetSkillsetByName() {
        return new GetSkillsetByName();
    }

    /**
     * Create an instance of {@link GetSkillsetByNameResponse }
     * 
     */
    public GetSkillsetByNameResponse createGetSkillsetByNameResponse() {
        return new GetSkillsetByNameResponse();
    }

    /**
     * Create an instance of {@link ReadSkillsetByName }
     * 
     */
    public ReadSkillsetByName createReadSkillsetByName() {
        return new ReadSkillsetByName();
    }

    /**
     * Create an instance of {@link ReadSkillsetByNameResponse }
     * 
     */
    public ReadSkillsetByNameResponse createReadSkillsetByNameResponse() {
        return new ReadSkillsetByNameResponse();
    }

    /**
     * Create an instance of {@link IsSkillsetInService }
     * 
     */
    public IsSkillsetInService createIsSkillsetInService() {
        return new IsSkillsetInService();
    }

    /**
     * Create an instance of {@link IsSkillsetInServiceResponse }
     * 
     */
    public IsSkillsetInServiceResponse createIsSkillsetInServiceResponse() {
        return new IsSkillsetInServiceResponse();
    }

    /**
     * Create an instance of {@link IsSkillsetNameInService }
     * 
     */
    public IsSkillsetNameInService createIsSkillsetNameInService() {
        return new IsSkillsetNameInService();
    }

    /**
     * Create an instance of {@link IsSkillsetNameInServiceResponse }
     * 
     */
    public IsSkillsetNameInServiceResponse createIsSkillsetNameInServiceResponse() {
        return new IsSkillsetNameInServiceResponse();
    }

    /**
     * Create an instance of {@link ArrayOfCISkillsetReadType }
     * 
     */
    public ArrayOfCISkillsetReadType createArrayOfCISkillsetReadType() {
        return new ArrayOfCISkillsetReadType();
    }

}
