//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:30:49 PM IST 
//


package com.koopid.ccmm.wsdl.ci_customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIActionReadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIActionReadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="contactID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="agent" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIAgentReadType" minOccurs="0"/&gt;
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="textHTML" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callbackTime" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIDateTime" minOccurs="0"/&gt;
 *         &lt;element name="callbackStatus" type="{http://datatypes.ci.ccmm.applications.nortel.com}CICallbackStatus"/&gt;
 *         &lt;element name="creationTime" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIDateTime" minOccurs="0"/&gt;
 *         &lt;element name="source" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIActionSource"/&gt;
 *         &lt;element name="mailTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mailCC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mailBCC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="timeAllocated" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="numberUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="outboundTalkTime" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="outboundDispositionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="actionType" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIContactType"/&gt;
 *         &lt;element name="customFieldList" type="{http://datatypes.ci.ccmm.applications.nortel.com}ArrayOfCICustomFieldReadType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIActionReadType", namespace = "http://datatypes.ci.ccmm.applications.nortel.com", propOrder = {
    "id",
    "contactID",
    "agent",
    "subject",
    "text",
    "textHTML",
    "callbackTime",
    "callbackStatus",
    "creationTime",
    "source",
    "mailTo",
    "mailCC",
    "mailBCC",
    "comment",
    "timeAllocated",
    "numberUsed",
    "outboundTalkTime",
    "outboundDispositionCode",
    "actionType",
    "customFieldList"
})
public class CIActionReadType {

    protected long id;
    protected long contactID;
    protected CIAgentReadType agent;
    protected String subject;
    protected String text;
    protected String textHTML;
    protected CIDateTime callbackTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CICallbackStatus callbackStatus;
    protected CIDateTime creationTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CIActionSource source;
    protected String mailTo;
    protected String mailCC;
    protected String mailBCC;
    protected String comment;
    protected long timeAllocated;
    protected String numberUsed;
    protected long outboundTalkTime;
    protected String outboundDispositionCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CIContactType actionType;
    protected ArrayOfCICustomFieldReadType customFieldList;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the contactID property.
     * 
     */
    public long getContactID() {
        return contactID;
    }

    /**
     * Sets the value of the contactID property.
     * 
     */
    public void setContactID(long value) {
        this.contactID = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link CIAgentReadType }
     *     
     */
    public CIAgentReadType getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIAgentReadType }
     *     
     */
    public void setAgent(CIAgentReadType value) {
        this.agent = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textHTML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextHTML() {
        return textHTML;
    }

    /**
     * Sets the value of the textHTML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextHTML(String value) {
        this.textHTML = value;
    }

    /**
     * Gets the value of the callbackTime property.
     * 
     * @return
     *     possible object is
     *     {@link CIDateTime }
     *     
     */
    public CIDateTime getCallbackTime() {
        return callbackTime;
    }

    /**
     * Sets the value of the callbackTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIDateTime }
     *     
     */
    public void setCallbackTime(CIDateTime value) {
        this.callbackTime = value;
    }

    /**
     * Gets the value of the callbackStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CICallbackStatus }
     *     
     */
    public CICallbackStatus getCallbackStatus() {
        return callbackStatus;
    }

    /**
     * Sets the value of the callbackStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CICallbackStatus }
     *     
     */
    public void setCallbackStatus(CICallbackStatus value) {
        this.callbackStatus = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link CIDateTime }
     *     
     */
    public CIDateTime getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIDateTime }
     *     
     */
    public void setCreationTime(CIDateTime value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link CIActionSource }
     *     
     */
    public CIActionSource getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIActionSource }
     *     
     */
    public void setSource(CIActionSource value) {
        this.source = value;
    }

    /**
     * Gets the value of the mailTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailTo() {
        return mailTo;
    }

    /**
     * Sets the value of the mailTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailTo(String value) {
        this.mailTo = value;
    }

    /**
     * Gets the value of the mailCC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailCC() {
        return mailCC;
    }

    /**
     * Sets the value of the mailCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailCC(String value) {
        this.mailCC = value;
    }

    /**
     * Gets the value of the mailBCC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailBCC() {
        return mailBCC;
    }

    /**
     * Sets the value of the mailBCC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailBCC(String value) {
        this.mailBCC = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the timeAllocated property.
     * 
     */
    public long getTimeAllocated() {
        return timeAllocated;
    }

    /**
     * Sets the value of the timeAllocated property.
     * 
     */
    public void setTimeAllocated(long value) {
        this.timeAllocated = value;
    }

    /**
     * Gets the value of the numberUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberUsed() {
        return numberUsed;
    }

    /**
     * Sets the value of the numberUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberUsed(String value) {
        this.numberUsed = value;
    }

    /**
     * Gets the value of the outboundTalkTime property.
     * 
     */
    public long getOutboundTalkTime() {
        return outboundTalkTime;
    }

    /**
     * Sets the value of the outboundTalkTime property.
     * 
     */
    public void setOutboundTalkTime(long value) {
        this.outboundTalkTime = value;
    }

    /**
     * Gets the value of the outboundDispositionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutboundDispositionCode() {
        return outboundDispositionCode;
    }

    /**
     * Sets the value of the outboundDispositionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutboundDispositionCode(String value) {
        this.outboundDispositionCode = value;
    }

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link CIContactType }
     *     
     */
    public CIContactType getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIContactType }
     *     
     */
    public void setActionType(CIContactType value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the customFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCICustomFieldReadType }
     *     
     */
    public ArrayOfCICustomFieldReadType getCustomFieldList() {
        return customFieldList;
    }

    /**
     * Sets the value of the customFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCICustomFieldReadType }
     *     
     */
    public void setCustomFieldList(ArrayOfCICustomFieldReadType value) {
        this.customFieldList = value;
    }

}
