//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:30:49 PM IST 
//


package com.koopid.ccmm.wsdl.ci_customer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIContactWriteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIContactWriteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="skillsetID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="priority" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIContactPriority"/&gt;
 *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="textHTML" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="callbackTime" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIDateTime"/&gt;
 *         &lt;element name="webOnHoldTag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="customFields" type="{http://datatypes.ci.ccmm.applications.nortel.com}CICustomFieldWriteType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIContactWriteType", namespace = "http://datatypes.ci.ccmm.applications.nortel.com", propOrder = {
    "skillsetID",
    "priority",
    "timezone",
    "text",
    "textHTML",
    "subject",
    "callbackTime",
    "webOnHoldTag",
    "customFields"
})
public class CIContactWriteType {

    protected long skillsetID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CIContactPriority priority;
    protected short timezone;
    protected String text;
    protected String textHTML;
    protected String subject;
    @XmlElement(required = true, nillable = true)
    protected CIDateTime callbackTime;
    protected String webOnHoldTag;
    @XmlElement(nillable = true)
    protected List<CICustomFieldWriteType> customFields;

    /**
     * Gets the value of the skillsetID property.
     * 
     */
    public long getSkillsetID() {
        return skillsetID;
    }

    /**
     * Sets the value of the skillsetID property.
     * 
     */
    public void setSkillsetID(long value) {
        this.skillsetID = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link CIContactPriority }
     *     
     */
    public CIContactPriority getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIContactPriority }
     *     
     */
    public void setPriority(CIContactPriority value) {
        this.priority = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     */
    public short getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     */
    public void setTimezone(short value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textHTML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextHTML() {
        return textHTML;
    }

    /**
     * Sets the value of the textHTML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextHTML(String value) {
        this.textHTML = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the callbackTime property.
     * 
     * @return
     *     possible object is
     *     {@link CIDateTime }
     *     
     */
    public CIDateTime getCallbackTime() {
        return callbackTime;
    }

    /**
     * Sets the value of the callbackTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIDateTime }
     *     
     */
    public void setCallbackTime(CIDateTime value) {
        this.callbackTime = value;
    }

    /**
     * Gets the value of the webOnHoldTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebOnHoldTag() {
        return webOnHoldTag;
    }

    /**
     * Sets the value of the webOnHoldTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebOnHoldTag(String value) {
        this.webOnHoldTag = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customFields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CICustomFieldWriteType }
     * 
     * 
     */
    public List<CICustomFieldWriteType> getCustomFields() {
        if (customFields == null) {
            customFields = new ArrayList<CICustomFieldWriteType>();
        }
        return this.customFields;
    }

}
