//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:30:49 PM IST 
//


package com.koopid.ccmm.wsdl.ci_customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIPhoneNumberWriteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIPhoneNumberWriteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="internationalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="areaCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phoneNumberType" type="{http://datatypes.ci.ccmm.applications.nortel.com}CIPhoneNumberType"/&gt;
 *         &lt;element name="doNotCall" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="doNotCallSpecified" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="defaultPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="defaultPhoneNumberSpecified" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIPhoneNumberWriteType", namespace = "http://datatypes.ci.ccmm.applications.nortel.com", propOrder = {
    "internationalCode",
    "areaCode",
    "number",
    "phoneNumberType",
    "doNotCall",
    "doNotCallSpecified",
    "defaultPhoneNumber",
    "defaultPhoneNumberSpecified"
})
public class CIPhoneNumberWriteType {

    protected String internationalCode;
    protected String areaCode;
    protected String number;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CIPhoneNumberType phoneNumberType;
    protected Boolean doNotCall;
    protected boolean doNotCallSpecified;
    protected Boolean defaultPhoneNumber;
    protected boolean defaultPhoneNumberSpecified;

    /**
     * Gets the value of the internationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalCode() {
        return internationalCode;
    }

    /**
     * Sets the value of the internationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalCode(String value) {
        this.internationalCode = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the phoneNumberType property.
     * 
     * @return
     *     possible object is
     *     {@link CIPhoneNumberType }
     *     
     */
    public CIPhoneNumberType getPhoneNumberType() {
        return phoneNumberType;
    }

    /**
     * Sets the value of the phoneNumberType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIPhoneNumberType }
     *     
     */
    public void setPhoneNumberType(CIPhoneNumberType value) {
        this.phoneNumberType = value;
    }

    /**
     * Gets the value of the doNotCall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDoNotCall() {
        return doNotCall;
    }

    /**
     * Sets the value of the doNotCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDoNotCall(Boolean value) {
        this.doNotCall = value;
    }

    /**
     * Gets the value of the doNotCallSpecified property.
     * 
     */
    public boolean isDoNotCallSpecified() {
        return doNotCallSpecified;
    }

    /**
     * Sets the value of the doNotCallSpecified property.
     * 
     */
    public void setDoNotCallSpecified(boolean value) {
        this.doNotCallSpecified = value;
    }

    /**
     * Gets the value of the defaultPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDefaultPhoneNumber() {
        return defaultPhoneNumber;
    }

    /**
     * Sets the value of the defaultPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefaultPhoneNumber(Boolean value) {
        this.defaultPhoneNumber = value;
    }

    /**
     * Gets the value of the defaultPhoneNumberSpecified property.
     * 
     */
    public boolean isDefaultPhoneNumberSpecified() {
        return defaultPhoneNumberSpecified;
    }

    /**
     * Sets the value of the defaultPhoneNumberSpecified property.
     * 
     */
    public void setDefaultPhoneNumberSpecified(boolean value) {
        this.defaultPhoneNumberSpecified = value;
    }

}
