//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:30:49 PM IST 
//


package com.koopid.ccmm.wsdl.ci_customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetCustomerByUsernameResult" type="{http://datatypes.ci.ccmm.applications.nortel.com}CICustomerReadType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getCustomerByUsernameResult"
})
@XmlRootElement(name = "GetCustomerByUsernameResponse")
public class GetCustomerByUsernameResponse {

    @XmlElement(name = "GetCustomerByUsernameResult")
    protected CICustomerReadType getCustomerByUsernameResult;

    /**
     * Gets the value of the getCustomerByUsernameResult property.
     * 
     * @return
     *     possible object is
     *     {@link CICustomerReadType }
     *     
     */
    public CICustomerReadType getGetCustomerByUsernameResult() {
        return getCustomerByUsernameResult;
    }

    /**
     * Sets the value of the getCustomerByUsernameResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link CICustomerReadType }
     *     
     */
    public void setGetCustomerByUsernameResult(CICustomerReadType value) {
        this.getCustomerByUsernameResult = value;
    }

}
