//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:30:49 PM IST 
//


package com.koopid.ccmm.wsdl.ci_customer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.koopid.ccmm.wsdl.ci_customer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.koopid.ccmm.wsdl.ci_customer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterNewCustomer }
     * 
     */
    public RegisterNewCustomer createRegisterNewCustomer() {
        return new RegisterNewCustomer();
    }

    /**
     * Create an instance of {@link CICustomerWriteType }
     * 
     */
    public CICustomerWriteType createCICustomerWriteType() {
        return new CICustomerWriteType();
    }

    /**
     * Create an instance of {@link CIPhoneNumberWriteType }
     * 
     */
    public CIPhoneNumberWriteType createCIPhoneNumberWriteType() {
        return new CIPhoneNumberWriteType();
    }

    /**
     * Create an instance of {@link CIAddressWriteType }
     * 
     */
    public CIAddressWriteType createCIAddressWriteType() {
        return new CIAddressWriteType();
    }

    /**
     * Create an instance of {@link CIEmailAddressWriteType }
     * 
     */
    public CIEmailAddressWriteType createCIEmailAddressWriteType() {
        return new CIEmailAddressWriteType();
    }

    /**
     * Create an instance of {@link RegisterNewCustomerResponse }
     * 
     */
    public RegisterNewCustomerResponse createRegisterNewCustomerResponse() {
        return new RegisterNewCustomerResponse();
    }

    /**
     * Create an instance of {@link RegisterAnonymousCustomer }
     * 
     */
    public RegisterAnonymousCustomer createRegisterAnonymousCustomer() {
        return new RegisterAnonymousCustomer();
    }

    /**
     * Create an instance of {@link RegisterAnonymousCustomerResponse }
     * 
     */
    public RegisterAnonymousCustomerResponse createRegisterAnonymousCustomerResponse() {
        return new RegisterAnonymousCustomerResponse();
    }

    /**
     * Create an instance of {@link RequestTextChat }
     * 
     */
    public RequestTextChat createRequestTextChat() {
        return new RequestTextChat();
    }

    /**
     * Create an instance of {@link CIContactWriteType }
     * 
     */
    public CIContactWriteType createCIContactWriteType() {
        return new CIContactWriteType();
    }

    /**
     * Create an instance of {@link RequestTextChatResponse }
     * 
     */
    public RequestTextChatResponse createRequestTextChatResponse() {
        return new RequestTextChatResponse();
    }

    /**
     * Create an instance of {@link RequestScheduledCallback }
     * 
     */
    public RequestScheduledCallback createRequestScheduledCallback() {
        return new RequestScheduledCallback();
    }

    /**
     * Create an instance of {@link RequestScheduledCallbackResponse }
     * 
     */
    public RequestScheduledCallbackResponse createRequestScheduledCallbackResponse() {
        return new RequestScheduledCallbackResponse();
    }

    /**
     * Create an instance of {@link RequestScheduledCallbackUTC }
     * 
     */
    public RequestScheduledCallbackUTC createRequestScheduledCallbackUTC() {
        return new RequestScheduledCallbackUTC();
    }

    /**
     * Create an instance of {@link RequestScheduledCallbackUTCResponse }
     * 
     */
    public RequestScheduledCallbackUTCResponse createRequestScheduledCallbackUTCResponse() {
        return new RequestScheduledCallbackUTCResponse();
    }

    /**
     * Create an instance of {@link RequestImmediateCallback }
     * 
     */
    public RequestImmediateCallback createRequestImmediateCallback() {
        return new RequestImmediateCallback();
    }

    /**
     * Create an instance of {@link RequestImmediateCallbackResponse }
     * 
     */
    public RequestImmediateCallbackResponse createRequestImmediateCallbackResponse() {
        return new RequestImmediateCallbackResponse();
    }

    /**
     * Create an instance of {@link SendPasswordReminder }
     * 
     */
    public SendPasswordReminder createSendPasswordReminder() {
        return new SendPasswordReminder();
    }

    /**
     * Create an instance of {@link SendPasswordReminderResponse }
     * 
     */
    public SendPasswordReminderResponse createSendPasswordReminderResponse() {
        return new SendPasswordReminderResponse();
    }

    /**
     * Create an instance of {@link ReadFirstBlockOfContacts }
     * 
     */
    public ReadFirstBlockOfContacts createReadFirstBlockOfContacts() {
        return new ReadFirstBlockOfContacts();
    }

    /**
     * Create an instance of {@link ReadFirstBlockOfContactsResponse }
     * 
     */
    public ReadFirstBlockOfContactsResponse createReadFirstBlockOfContactsResponse() {
        return new ReadFirstBlockOfContactsResponse();
    }

    /**
     * Create an instance of {@link CIContactBlockReadType }
     * 
     */
    public CIContactBlockReadType createCIContactBlockReadType() {
        return new CIContactBlockReadType();
    }

    /**
     * Create an instance of {@link ReadLastBlockOfContacts }
     * 
     */
    public ReadLastBlockOfContacts createReadLastBlockOfContacts() {
        return new ReadLastBlockOfContacts();
    }

    /**
     * Create an instance of {@link ReadLastBlockOfContactsResponse }
     * 
     */
    public ReadLastBlockOfContactsResponse createReadLastBlockOfContactsResponse() {
        return new ReadLastBlockOfContactsResponse();
    }

    /**
     * Create an instance of {@link ReadPreviousBlockOfContacts }
     * 
     */
    public ReadPreviousBlockOfContacts createReadPreviousBlockOfContacts() {
        return new ReadPreviousBlockOfContacts();
    }

    /**
     * Create an instance of {@link ReadPreviousBlockOfContactsResponse }
     * 
     */
    public ReadPreviousBlockOfContactsResponse createReadPreviousBlockOfContactsResponse() {
        return new ReadPreviousBlockOfContactsResponse();
    }

    /**
     * Create an instance of {@link ReadNextBlockOfContacts }
     * 
     */
    public ReadNextBlockOfContacts createReadNextBlockOfContacts() {
        return new ReadNextBlockOfContacts();
    }

    /**
     * Create an instance of {@link ReadNextBlockOfContactsResponse }
     * 
     */
    public ReadNextBlockOfContactsResponse createReadNextBlockOfContactsResponse() {
        return new ReadNextBlockOfContactsResponse();
    }

    /**
     * Create an instance of {@link GetNumberOfContactsByTime }
     * 
     */
    public GetNumberOfContactsByTime createGetNumberOfContactsByTime() {
        return new GetNumberOfContactsByTime();
    }

    /**
     * Create an instance of {@link CIDateTime }
     * 
     */
    public CIDateTime createCIDateTime() {
        return new CIDateTime();
    }

    /**
     * Create an instance of {@link GetNumberOfContactsByTimeResponse }
     * 
     */
    public GetNumberOfContactsByTimeResponse createGetNumberOfContactsByTimeResponse() {
        return new GetNumberOfContactsByTimeResponse();
    }

    /**
     * Create an instance of {@link ReadCustomer }
     * 
     */
    public ReadCustomer createReadCustomer() {
        return new ReadCustomer();
    }

    /**
     * Create an instance of {@link ReadCustomerResponse }
     * 
     */
    public ReadCustomerResponse createReadCustomerResponse() {
        return new ReadCustomerResponse();
    }

    /**
     * Create an instance of {@link CICustomerReadType }
     * 
     */
    public CICustomerReadType createCICustomerReadType() {
        return new CICustomerReadType();
    }

    /**
     * Create an instance of {@link GetDefaultAddress }
     * 
     */
    public GetDefaultAddress createGetDefaultAddress() {
        return new GetDefaultAddress();
    }

    /**
     * Create an instance of {@link GetDefaultAddressResponse }
     * 
     */
    public GetDefaultAddressResponse createGetDefaultAddressResponse() {
        return new GetDefaultAddressResponse();
    }

    /**
     * Create an instance of {@link CIAddressReadType }
     * 
     */
    public CIAddressReadType createCIAddressReadType() {
        return new CIAddressReadType();
    }

    /**
     * Create an instance of {@link GetDefaultPhoneNumber }
     * 
     */
    public GetDefaultPhoneNumber createGetDefaultPhoneNumber() {
        return new GetDefaultPhoneNumber();
    }

    /**
     * Create an instance of {@link GetDefaultPhoneNumberResponse }
     * 
     */
    public GetDefaultPhoneNumberResponse createGetDefaultPhoneNumberResponse() {
        return new GetDefaultPhoneNumberResponse();
    }

    /**
     * Create an instance of {@link CIPhoneNumberReadType }
     * 
     */
    public CIPhoneNumberReadType createCIPhoneNumberReadType() {
        return new CIPhoneNumberReadType();
    }

    /**
     * Create an instance of {@link GetDefaultEmailAddress }
     * 
     */
    public GetDefaultEmailAddress createGetDefaultEmailAddress() {
        return new GetDefaultEmailAddress();
    }

    /**
     * Create an instance of {@link GetDefaultEmailAddressResponse }
     * 
     */
    public GetDefaultEmailAddressResponse createGetDefaultEmailAddressResponse() {
        return new GetDefaultEmailAddressResponse();
    }

    /**
     * Create an instance of {@link CIEmailAddressReadType }
     * 
     */
    public CIEmailAddressReadType createCIEmailAddressReadType() {
        return new CIEmailAddressReadType();
    }

    /**
     * Create an instance of {@link GetCustomerByUsername }
     * 
     */
    public GetCustomerByUsername createGetCustomerByUsername() {
        return new GetCustomerByUsername();
    }

    /**
     * Create an instance of {@link GetCustomerByUsernameResponse }
     * 
     */
    public GetCustomerByUsernameResponse createGetCustomerByUsernameResponse() {
        return new GetCustomerByUsernameResponse();
    }

    /**
     * Create an instance of {@link GetCustomerByEmailAddress }
     * 
     */
    public GetCustomerByEmailAddress createGetCustomerByEmailAddress() {
        return new GetCustomerByEmailAddress();
    }

    /**
     * Create an instance of {@link GetCustomerByEmailAddressResponse }
     * 
     */
    public GetCustomerByEmailAddressResponse createGetCustomerByEmailAddressResponse() {
        return new GetCustomerByEmailAddressResponse();
    }

    /**
     * Create an instance of {@link GetCustomerByPhoneNumber }
     * 
     */
    public GetCustomerByPhoneNumber createGetCustomerByPhoneNumber() {
        return new GetCustomerByPhoneNumber();
    }

    /**
     * Create an instance of {@link GetCustomerByPhoneNumberResponse }
     * 
     */
    public GetCustomerByPhoneNumberResponse createGetCustomerByPhoneNumberResponse() {
        return new GetCustomerByPhoneNumberResponse();
    }

    /**
     * Create an instance of {@link CIMultipleCustomerIDReadType }
     * 
     */
    public CIMultipleCustomerIDReadType createCIMultipleCustomerIDReadType() {
        return new CIMultipleCustomerIDReadType();
    }

    /**
     * Create an instance of {@link GetCustomerByFirstName }
     * 
     */
    public GetCustomerByFirstName createGetCustomerByFirstName() {
        return new GetCustomerByFirstName();
    }

    /**
     * Create an instance of {@link GetCustomerByFirstNameResponse }
     * 
     */
    public GetCustomerByFirstNameResponse createGetCustomerByFirstNameResponse() {
        return new GetCustomerByFirstNameResponse();
    }

    /**
     * Create an instance of {@link GetCustomerByLastName }
     * 
     */
    public GetCustomerByLastName createGetCustomerByLastName() {
        return new GetCustomerByLastName();
    }

    /**
     * Create an instance of {@link GetCustomerByLastNameResponse }
     * 
     */
    public GetCustomerByLastNameResponse createGetCustomerByLastNameResponse() {
        return new GetCustomerByLastNameResponse();
    }

    /**
     * Create an instance of {@link GetCustomerByName }
     * 
     */
    public GetCustomerByName createGetCustomerByName() {
        return new GetCustomerByName();
    }

    /**
     * Create an instance of {@link GetCustomerByNameResponse }
     * 
     */
    public GetCustomerByNameResponse createGetCustomerByNameResponse() {
        return new GetCustomerByNameResponse();
    }

    /**
     * Create an instance of {@link UpdateTitle }
     * 
     */
    public UpdateTitle createUpdateTitle() {
        return new UpdateTitle();
    }

    /**
     * Create an instance of {@link UpdateTitleResponse }
     * 
     */
    public UpdateTitleResponse createUpdateTitleResponse() {
        return new UpdateTitleResponse();
    }

    /**
     * Create an instance of {@link UpdateFirstName }
     * 
     */
    public UpdateFirstName createUpdateFirstName() {
        return new UpdateFirstName();
    }

    /**
     * Create an instance of {@link UpdateFirstNameResponse }
     * 
     */
    public UpdateFirstNameResponse createUpdateFirstNameResponse() {
        return new UpdateFirstNameResponse();
    }

    /**
     * Create an instance of {@link UpdateLastName }
     * 
     */
    public UpdateLastName createUpdateLastName() {
        return new UpdateLastName();
    }

    /**
     * Create an instance of {@link UpdateLastNameResponse }
     * 
     */
    public UpdateLastNameResponse createUpdateLastNameResponse() {
        return new UpdateLastNameResponse();
    }

    /**
     * Create an instance of {@link UpdateUsername }
     * 
     */
    public UpdateUsername createUpdateUsername() {
        return new UpdateUsername();
    }

    /**
     * Create an instance of {@link UpdateUsernameResponse }
     * 
     */
    public UpdateUsernameResponse createUpdateUsernameResponse() {
        return new UpdateUsernameResponse();
    }

    /**
     * Create an instance of {@link UpdatePassword }
     * 
     */
    public UpdatePassword createUpdatePassword() {
        return new UpdatePassword();
    }

    /**
     * Create an instance of {@link UpdatePasswordResponse }
     * 
     */
    public UpdatePasswordResponse createUpdatePasswordResponse() {
        return new UpdatePasswordResponse();
    }

    /**
     * Create an instance of {@link UpdateCustomer }
     * 
     */
    public UpdateCustomer createUpdateCustomer() {
        return new UpdateCustomer();
    }

    /**
     * Create an instance of {@link UpdateCustomerResponse }
     * 
     */
    public UpdateCustomerResponse createUpdateCustomerResponse() {
        return new UpdateCustomerResponse();
    }

    /**
     * Create an instance of {@link AddAddress }
     * 
     */
    public AddAddress createAddAddress() {
        return new AddAddress();
    }

    /**
     * Create an instance of {@link AddAddressResponse }
     * 
     */
    public AddAddressResponse createAddAddressResponse() {
        return new AddAddressResponse();
    }

    /**
     * Create an instance of {@link AddPhoneNumber }
     * 
     */
    public AddPhoneNumber createAddPhoneNumber() {
        return new AddPhoneNumber();
    }

    /**
     * Create an instance of {@link AddPhoneNumberResponse }
     * 
     */
    public AddPhoneNumberResponse createAddPhoneNumberResponse() {
        return new AddPhoneNumberResponse();
    }

    /**
     * Create an instance of {@link AddEmailAddress }
     * 
     */
    public AddEmailAddress createAddEmailAddress() {
        return new AddEmailAddress();
    }

    /**
     * Create an instance of {@link AddEmailAddressResponse }
     * 
     */
    public AddEmailAddressResponse createAddEmailAddressResponse() {
        return new AddEmailAddressResponse();
    }

    /**
     * Create an instance of {@link AddCustomField }
     * 
     */
    public AddCustomField createAddCustomField() {
        return new AddCustomField();
    }

    /**
     * Create an instance of {@link CICustomFieldWriteType }
     * 
     */
    public CICustomFieldWriteType createCICustomFieldWriteType() {
        return new CICustomFieldWriteType();
    }

    /**
     * Create an instance of {@link AddCustomFieldResponse }
     * 
     */
    public AddCustomFieldResponse createAddCustomFieldResponse() {
        return new AddCustomFieldResponse();
    }

    /**
     * Create an instance of {@link RemoveAddress }
     * 
     */
    public RemoveAddress createRemoveAddress() {
        return new RemoveAddress();
    }

    /**
     * Create an instance of {@link RemoveAddressResponse }
     * 
     */
    public RemoveAddressResponse createRemoveAddressResponse() {
        return new RemoveAddressResponse();
    }

    /**
     * Create an instance of {@link RemovePhoneNumber }
     * 
     */
    public RemovePhoneNumber createRemovePhoneNumber() {
        return new RemovePhoneNumber();
    }

    /**
     * Create an instance of {@link RemovePhoneNumberResponse }
     * 
     */
    public RemovePhoneNumberResponse createRemovePhoneNumberResponse() {
        return new RemovePhoneNumberResponse();
    }

    /**
     * Create an instance of {@link RemoveEmailAddress }
     * 
     */
    public RemoveEmailAddress createRemoveEmailAddress() {
        return new RemoveEmailAddress();
    }

    /**
     * Create an instance of {@link RemoveEmailAddressResponse }
     * 
     */
    public RemoveEmailAddressResponse createRemoveEmailAddressResponse() {
        return new RemoveEmailAddressResponse();
    }

    /**
     * Create an instance of {@link RemoveCustomField }
     * 
     */
    public RemoveCustomField createRemoveCustomField() {
        return new RemoveCustomField();
    }

    /**
     * Create an instance of {@link RemoveCustomFieldResponse }
     * 
     */
    public RemoveCustomFieldResponse createRemoveCustomFieldResponse() {
        return new RemoveCustomFieldResponse();
    }

    /**
     * Create an instance of {@link ArrayOfCIContactReadType }
     * 
     */
    public ArrayOfCIContactReadType createArrayOfCIContactReadType() {
        return new ArrayOfCIContactReadType();
    }

    /**
     * Create an instance of {@link CIContactReadType }
     * 
     */
    public CIContactReadType createCIContactReadType() {
        return new CIContactReadType();
    }

    /**
     * Create an instance of {@link CISkillsetReadType }
     * 
     */
    public CISkillsetReadType createCISkillsetReadType() {
        return new CISkillsetReadType();
    }

    /**
     * Create an instance of {@link CIAgentReadType }
     * 
     */
    public CIAgentReadType createCIAgentReadType() {
        return new CIAgentReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIActionReadType }
     * 
     */
    public ArrayOfCIActionReadType createArrayOfCIActionReadType() {
        return new ArrayOfCIActionReadType();
    }

    /**
     * Create an instance of {@link CIActionReadType }
     * 
     */
    public CIActionReadType createCIActionReadType() {
        return new CIActionReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCICustomFieldReadType }
     * 
     */
    public ArrayOfCICustomFieldReadType createArrayOfCICustomFieldReadType() {
        return new ArrayOfCICustomFieldReadType();
    }

    /**
     * Create an instance of {@link CICustomFieldReadType }
     * 
     */
    public CICustomFieldReadType createCICustomFieldReadType() {
        return new CICustomFieldReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIAddressReadType }
     * 
     */
    public ArrayOfCIAddressReadType createArrayOfCIAddressReadType() {
        return new ArrayOfCIAddressReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIPhoneNumberReadType }
     * 
     */
    public ArrayOfCIPhoneNumberReadType createArrayOfCIPhoneNumberReadType() {
        return new ArrayOfCIPhoneNumberReadType();
    }

    /**
     * Create an instance of {@link ArrayOfCIEmailAddressReadType }
     * 
     */
    public ArrayOfCIEmailAddressReadType createArrayOfCIEmailAddressReadType() {
        return new ArrayOfCIEmailAddressReadType();
    }

    /**
     * Create an instance of {@link ArrayOfLong }
     * 
     */
    public ArrayOfLong createArrayOfLong() {
        return new ArrayOfLong();
    }

}
