//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 03:30:49 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.ci.ccmm.applications.nortel.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.koopid.ccmm.wsdl.ci_customer;
